create table actor(
    id   int primary key generated by default as identity,
    name varchar(100) not null unique,
    age  int check ( age > 100 )
);

create table movie(
    id           int primary key generated by default as identity,
    name         varchar(200) not null,
    year_of_prod int check (year_of_prod > 1900)
);

create table actor_movie(
    actor_id int references actor (id),
    movie_id int references movie (id),
    primary key (actor_id, movie_id)
)