create table person (
                        id int generated by default as identity primary key,
                        name varchar unique,
                        age int
);

create table book (
                      id int generated by default as identity,
                      name varchar,
                      author varchar,
                      year int,
                      owner int references person(id)
);
