create table Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) not null,
                       age int,
                       email varchar(100)
);

insert into person(name, age, email)
values ('mark', 20, 'mark@mark.mk');

